name: ridy
description: Driver application of Ridy

publish_to: 'none'

version: 2.3.2+116

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  artemis: ^7.13.1
  country_code_picker: ^3.3.0
  country_codes: ^3.3.0
  dotted_line: ^3.1.0
  equatable: ^2.0.5
  file_picker: ^10.2.0
  firebase_analytics: ^11.5.0
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  firebase_crashlytics: ^4.3.7
  firebase_messaging: ^15.2.7
  fl_chart: ^0.55.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_chat_types: ^3.4.3
  flutter_chat_ui: ^1.6.2
  flutter_chat_core: ^2.0.0
  flutter_map: ^3.0.0
  flutter_map_location_marker: ^5.0.0+1
  flutter_svg: ^2.0.9
  flutter_vector_icons: ^2.0.0
  geolocator: ^9.0.2
  google_fonts: ^4.0.4
  google_maps_flutter: ^2.2.1
  graphql_flutter: ^5.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  intl: ^0.20.2
  json_annotation: ^4.5.0
  latlong2: ^0.8.1
  lifecycle: ^0.10.0
  map_launcher: ^3.5.0
  meta: ^1.3.0
  modal_bottom_sheet: ^3.0.0
  package_info_plus: ^8.3.0
  pinput: ^5.0.1
  shimmer: ^3.0.0
  timeago_flutter: ^3.7.0
  url_launcher: ^6.1.6
  velocity_x: ^4.3.1


dev_dependencies:
  build_runner: ^2.1.10
  flutter_lints: ^6.0.0
  json_serializable: ^6.2.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/dotted-lines-1.png
    - images/registration-illustration.png
    - images/logo.png
    - images/marker.png
    - images/marker_pickup.png
    - images/marker_destination.png
    - google_fonts/

flutter_intl:
  enabled: true
